def NoSelectedScenario ():
    print ('')
    print ('')
    print ('')

    print ('******************** ERROR ****************************')
    print ('*                                                     *')
    print ('*                                                     *')    
    print ('* No scenario has been seceted to simulate            *')
    print ('* All scenarios are FALSE in row TO RUN SIMULATION    *')
    print ('*                                                     *')
    print ('*                                                     *')  
    print ('*******************************************************')
    print ('')
    print ('')
    print ('')
